/**
 * Shared mood mappings for the travel mood discovery flow.
 *
 * These maps define the 18 predefined stage 2 moods organized by tone:
 * - Positive (6): Excited, Calm, Curious, Romantic, Confident, Playful
 * - Neutral (6): Balanced, Unsure, Focused, Low energy, Reflective, Open
 * - Negative (6): Stressed, Tired, Anxious, Burnt out, Overwhelmed, Lonely
 *
 * Each version serves a specific purpose:
 * - labelMapDisplay: Place venue names for UI stage 3 display in mood-flow
 * - labelMapSearch: Search keywords for Foursquare in place-suggestions
 * - toneMapDisplay: Tone-based venue names for stage 3 fallback display
 * - toneMapSearch: Tone-based search keywords for stage 3 fallback search
 */

export const PREDEFINED_STAGE2_MOODS = new Set([
  "excited",
  "calm",
  "curious",
  "romantic",
  "confident",
  "playful",
  "balanced",
  "unsure",
  "focused",
  "low energy",
  "reflective",
  "open",
  "stressed",
  "tired",
  "anxious",
  "burnt out",
  "overwhelmed",
  "lonely",
]);

export const labelMapDisplay = {
  anxious: [
    "Botanical gardens",
    "Green spaces",
    "Meditation centers",
    "Quiet museums",
    "Seaside parks",
    "Wellness studios",
    "Meditative temples",
    "Peaceful retreats",
  ],
  "burnt out": [
    "Calm waterfronts",
    "Detox spas",
    "Forest trails",
    "Hot springs",
    "Nature lodges",
    "Retreat centers",
    "Healing resorts",
    "Quiet sanctuaries",
  ],
  balanced: [
    "Cultural districts",
    "Local markets",
    "Museums",
    "Parks",
    "Quiet cafes",
    "Scenic walks",
    "Community gardens",
    "Public plazas",
  ],
  calm: [
    "Botanical gardens",
    "Lakes",
    "Nature reserves",
    "Scenic walks",
    "Tea houses",
    "Wellness centers",
    "Meditation gardens",
    "Peaceful temples",
  ],
  confident: [
    "City highlights",
    "Fine dining",
    "Landmarks",
    "Rooftops",
    "Signature experiences",
    "Stylish lounges",
    "Upscale resorts",
    "Designer districts",
  ],
  curious: [
    "Architecture tours",
    "Cultural centers",
    "Hidden gems",
    "Historic sites",
    "Museums",
    "Science centers",
    "Nature museums",
    "Discovery centers",
  ],
  excited: [
    "Adventure venues",
    "Live shows",
    "Music venues",
    "Nightlife",
    "Sports bars",
    "Theme parks",
    "Dance clubs",
    "Music festivals",
  ],
  focused: [
    "Coworking spaces",
    "Libraries",
    "Minimalist cafes",
    "Quiet cafes",
    "Reading rooms",
    "Study lounges",
    "Private studios",
    "Academic spaces",
  ],
  lonely: [
    "Community events",
    "Friendly spots",
    "Group activities",
    "Live music venues",
    "Local classes",
    "Social cafes",
    "Group tours",
    "Community centers",
  ],
  "low energy": [
    "Cozy cafes",
    "Gentle walks",
    "Quiet lounges",
    "Slow brunch spots",
    "Spas",
    "Tea rooms",
    "Slow lounges",
    "Rest havens",
  ],
  open: [
    "Galleries",
    "Hidden gems",
    "Local markets",
    "Neighborhood walks",
    "New experiences",
    "Street food areas",
    "Indie galleries",
    "Artisan markets",
  ],
  overwhelmed: [
    "Gentle itineraries",
    "Mindful spaces",
    "No-crowd areas",
    "Quiet parks",
    "Short walks",
    "Slow cafes",
    "Silent retreats",
    "Zen gardens",
  ],
  playful: [
    "Arcades",
    "Fun fairs",
    "Interactive museums",
    "Live shows",
    "Mini golf",
    "Street food",
    "Amusement parks",
    "Cartoon museums",
  ],
  reflective: [
    "Art galleries",
    "Memorials",
    "Old towns",
    "River walks",
    "Scenic viewpoints",
    "Temples",
    "Heritage sites",
    "Quiet courtyards",
  ],
  romantic: [
    "Fine dining",
    "Gardens",
    "River walks",
    "Rooftops",
    "Sunset spots",
    "Wine bars",
    "Candlelit restaurants",
    "Garden villas",
  ],
  stressed: [
    "Meditation spots",
    "Nature trails",
    "Quiet parks",
    "Slow cafes",
    "Spas",
    "Thermal baths",
    "Healing springs",
    "Peace sanctuaries",
  ],
  tired: [
    "Bookstores",
    "Cozy cafes",
    "Quiet lounges",
    "Slow brunch spots",
    "Spas",
    "Tea rooms",
    "Rest cafes",
    "Slow living spaces",
  ],
  unsure: [
    "Casual dining",
    "City highlights",
    "Easy itineraries",
    "Local favorites",
    "Mixed activities",
    "Walkable areas",
    "Popular destinations",
    "Diverse neighborhoods",
  ],
};

export const labelMapSearch = {
  anxious: [
    "botanical garden",
    "green space",
    "quiet museum",
    "seaside walk",
    "tea house",
    "wellness center",
    "meditative temple",
    "peaceful retreat",
  ],
  "burnt out": [
    "detox spa",
    "forest trail",
    "hot springs",
    "nature lodge",
    "retreat",
    "wellness resort",
    "healing center",
    "quiet sanctuary",
  ],
  balanced: [
    "cultural district",
    "local market",
    "museum",
    "neighborhood cafe",
    "park",
    "scenic walk",
    "community garden",
    "public plaza",
  ],
  calm: [
    "botanical garden",
    "lakeside park",
    "nature reserve",
    "quiet cafe",
    "spa",
    "tea house",
    "meditation garden",
    "peaceful temple",
  ],
  confident: [
    "chef table",
    "cocktail bar",
    "design district",
    "luxury lounge",
    "skyline viewpoint",
    "steakhouse",
    "upscale resort",
    "fine establishment",
  ],
  curious: [
    "architecture tour",
    "art gallery",
    "cultural center",
    "historic site",
    "museum",
    "science center",
    "nature museum",
    "discovery center",
  ],
  excited: [
    "arcade",
    "food market",
    "live music",
    "nightlife",
    "rooftop bar",
    "sports bar",
    "dance club",
    "music festival",
  ],
  focused: [
    "bookstore",
    "coworking",
    "library",
    "quiet lounge",
    "reading room",
    "study cafe",
    "private study",
    "academic library",
  ],
  lonely: [
    "board game cafe",
    "community events",
    "group class",
    "live music",
    "meetup spot",
    "social cafe",
    "group tour",
    "community center",
  ],
  "low energy": [
    "bakery",
    "cozy cafe",
    "gentle walk",
    "quiet park",
    "spa",
    "tea room",
    "slow lounge",
    "rest haven",
  ],
  open: [
    "cultural center",
    "gallery",
    "hidden gems",
    "local market",
    "neighborhood walk",
    "street food",
    "indie gallery",
    "artisan market",
  ],
  overwhelmed: [
    "gentle walk",
    "lakeside",
    "mindful space",
    "no-crowd area",
    "quiet park",
    "slow cafe",
    "silent retreat",
    "zen garden",
  ],
  playful: [
    "arcade",
    "comedy club",
    "escape room",
    "fun fair",
    "interactive museum",
    "mini golf",
    "amusement park",
    "cartoon museum",
  ],
  reflective: [
    "art gallery",
    "memorial",
    "old town",
    "river walk",
    "scenic viewpoint",
    "temple",
    "heritage site",
    "quiet courtyard",
  ],
  romantic: [
    "fine dining",
    "garden",
    "river walk",
    "rooftop lounge",
    "sunset spot",
    "wine bar",
    "candlelit restaurant",
    "garden villa",
  ],
  stressed: [
    "meditation center",
    "nature trail",
    "quiet park",
    "spa",
    "thermal baths",
    "wellness studio",
    "healing springs",
    "peace sanctuary",
  ],
  tired: [
    "bookstore",
    "cozy cafe",
    "quiet lounge",
    "slow brunch",
    "spa",
    "tea room",
    "rest cafe",
    "slow living space",
  ],
  unsure: [
    "casual dining",
    "city highlights",
    "easy itineraries",
    "local favorites",
    "mixed activities",
    "walkable area",
    "waterfront",
    "popular destination",
    "diverse neighborhood",
  ],
};

export const toneMapDisplay = {
  positive: [
    "Attractions",
    "Viewpoints",
    "Live music venues",
    "Food markets",
    "Rooftop bars",
    "Street food areas",
    "Entertainment hubs",
    "Night markets",
  ],
  neutral: [
    "Museums",
    "Libraries",
    "Coffee shops",
    "Galleries",
    "Bookstores",
    "Walking tours",
    "Community spaces",
    "Cultural centers",
  ],
  negative: [
    "Parks",
    "Spa centers",
    "Botanical gardens",
    "Quiet cafes",
    "Wellness centers",
    "Nature trails",
    "Healing resorts",
    "Meditation spaces",
  ],
};

export const toneMapSearch = {
  positive: [
    "attractions",
    "city highlights",
    "food market",
    "live music",
    "nightlife",
    "rooftop bar",
    "entertainment venue",
    "social hotspot",
  ],
  neutral: [
    "bookstore",
    "library",
    "local market",
    "museum",
    "quiet cafe",
    "scenic walk",
    "community space",
    "cultural hub",
  ],
  negative: [
    "botanical garden",
    "nature trail",
    "quiet park",
    "spa",
    "tea house",
    "wellness center",
    "healing space",
    "tranquil retreat",
  ],
};

export function getPrimaryFallbackKeywords(
  stage2Selection,
  stage1Tone,
  isSearchContext = false,
) {
  const stage2Lower = String(stage2Selection || "").
    toLowerCase()
    .trim();
  const stage1Lower = String(stage1Tone || "")
    .toLowerCase()
    .trim();

  const labelMap = isSearchContext ? labelMapSearch : labelMapDisplay;
  const toneMap = isSearchContext ? toneMapSearch : toneMapDisplay;

  if (labelMap[stage2Lower]) {
    return labelMap[stage2Lower];
  }

  return toneMap[stage1Lower] || toneMap.positive;
}
